AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20

inherit_mode:
  merge:
    - Exclude